-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyQ+JkdE9yWR9++aF
ufUdwb+POCERmovrnIP5MvrsONygCgYIKoZIzj0DAQehRANCAATCuOjWEQvESpT3
TfmP3h3k2y+B3GyX0g0A1h4bkprITYDA3YRolLueVHlE+ZF73Q0aC0XKWQ4WrMUI
vFEHGZai
-----END PRIVATE KEY-----